import { useState } from 'react';
import { phones } from '../data/phones';

export default function AICommunity() {
  const [selectedPhone, setSelectedPhone] = useState(phones[0]);
  const [loading, setLoading] = useState(false);
  const [generated, setGenerated] = useState(false);

  function analyze() {
    setGenerated(false);
    setLoading(true);
    setTimeout(() => { setLoading(false); setGenerated(true); }, 2500);
  }

  const data = {
    commentsAnalyzed: [3284, 5120, 2180, 1950, 1420, 2760][phones.indexOf(selectedPhone)] || 1284,
    positive: [62, 71, 67, 58, 64, 55][phones.indexOf(selectedPhone)] || 62,
    neutral: [24, 18, 21, 26, 22, 28][phones.indexOf(selectedPhone)] || 24,
    negative: [14, 11, 12, 16, 14, 17][phones.indexOf(selectedPhone)] || 14,
    topics: ['Camera', 'Battery', 'Performance', 'Display', 'Price', 'Design'],
    positive_points: selectedPhone.pros,
    negative_points: selectedPhone.cons,
    opinion: selectedPhone.rating >= 4.8
      ? `The ${selectedPhone.brand} ${selectedPhone.name} enjoys overwhelmingly positive community sentiment. Users consistently praise its camera performance and premium build. The most common complaint is its high price point, but most users feel it's justified by the overall experience.`
      : selectedPhone.rating >= 4.5
      ? `The ${selectedPhone.brand} ${selectedPhone.name} has strong community approval. Users are impressed with the value proposition and camera quality. Some concerns around heating and software experience are noted but don't significantly dampen overall satisfaction.`
      : `The ${selectedPhone.brand} ${selectedPhone.name} receives generally positive feedback for its price range. Community members highlight the display and battery as standouts. The camera lags behind flagship competitors according to reviewers.`,
  };

  return (
    <div className="max-w-4xl mx-auto px-4 py-6">
      <div className="mb-6">
        <h1 className="font-display text-2xl font-bold text-ink">AI Community Analysis</h1>
        <p className="text-sm text-muted mt-1">AI-powered analysis of community discussions and user opinions.</p>
      </div>

      <div className="flex items-start gap-3 p-3 bg-primary-light rounded-lg border border-primary/20 mb-6 text-xs">
        <svg className="w-4 h-4 text-primary shrink-0 mt-0.5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>
        <p className="text-primary/80"><span className="font-semibold text-primary">AI Prototype Insight</span> — Community analysis is generated by AI from prototype data. Sentiment figures are illustrative, not based on real-time community data collection.</p>
      </div>

      {/* Phone selector */}
      <div className="bg-surface rounded-lg border border-edge p-4 mb-4">
        <label className="text-sm font-display font-semibold text-ink mb-2 block">Select Phone to Analyze</label>
        <div className="flex flex-wrap gap-2">
          {phones.map(phone => (
            <button key={phone.id} onClick={() => { setSelectedPhone(phone); setGenerated(false); }} className={`flex items-center gap-2 px-3 py-2 rounded-lg border text-left transition-colors text-xs ${selectedPhone.id === phone.id ? 'border-primary bg-primary-light text-primary font-semibold' : 'border-edge text-muted hover:border-primary/40'}`}>
              {phone.brand} {phone.name}
            </button>
          ))}
        </div>
      </div>

      <div className="flex items-center gap-4 bg-surface rounded-lg border border-edge p-4 mb-4">
        <img src={selectedPhone.image} alt={selectedPhone.name} className="w-14 h-18 object-cover rounded bg-bg" style={{ height: '72px' }} />
        <div className="flex-1">
          <p className="text-xs text-muted">{selectedPhone.brand}</p>
          <p className="font-display font-bold text-ink">{selectedPhone.name}</p>
          <p className="text-xs text-muted mt-0.5">{selectedPhone.releaseDate}</p>
        </div>
        <button onClick={analyze} disabled={loading} className="px-5 py-2.5 bg-primary text-white text-sm font-semibold rounded-lg hover:bg-primary-dark transition-colors disabled:opacity-60 flex items-center gap-2">
          {loading ? <><span className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin" />Analyzing...</> : <>Analyze Community</>}
        </button>
      </div>

      {loading && (
        <div className="bg-surface rounded-lg border border-edge p-10 text-center">
          <div className="w-8 h-8 border-2 border-primary border-t-transparent rounded-full animate-spin mx-auto mb-3" />
          <p className="text-sm text-muted">Analyzing {data.commentsAnalyzed.toLocaleString()} community comments...</p>
          <p className="text-xs text-muted mt-1">Processing sentiment, topics, and user opinions.</p>
        </div>
      )}

      {generated && !loading && (
        <div className="space-y-5">
          {/* Sentiment overview */}
          <div className="grid grid-cols-1 sm:grid-cols-4 gap-3">
            <div className="bg-surface rounded-lg border border-edge p-4 text-center sm:col-span-1">
              <p className="text-3xl font-bold font-display text-ink">{data.commentsAnalyzed.toLocaleString()}</p>
              <p className="text-xs text-muted mt-1">Comments Analyzed</p>
            </div>
            <div className="bg-success-light rounded-lg border border-success/20 p-4 text-center">
              <p className="text-3xl font-bold font-display text-success">{data.positive}%</p>
              <p className="text-xs text-success/70 mt-1">Positive</p>
            </div>
            <div className="bg-bg rounded-lg border border-edge p-4 text-center">
              <p className="text-3xl font-bold font-display text-muted">{data.neutral}%</p>
              <p className="text-xs text-muted mt-1">Neutral</p>
            </div>
            <div className="bg-red-50 rounded-lg border border-red-100 p-4 text-center">
              <p className="text-3xl font-bold font-display text-danger">{data.negative}%</p>
              <p className="text-xs text-danger/70 mt-1">Negative</p>
            </div>
          </div>

          {/* Sentiment bar */}
          <div className="bg-surface rounded-lg border border-edge p-5">
            <h3 className="font-display font-bold text-ink mb-3">Overall Sentiment</h3>
            <div className="h-4 rounded-full overflow-hidden flex">
              <div className="bg-success h-full transition-all" style={{ width: `${data.positive}%` }} />
              <div className="bg-edge h-full transition-all" style={{ width: `${data.neutral}%` }} />
              <div className="bg-danger/60 h-full transition-all" style={{ width: `${data.negative}%` }} />
            </div>
            <div className="flex items-center gap-4 mt-2 text-xs text-muted">
              <span className="flex items-center gap-1"><span className="w-2 h-2 bg-success rounded-full inline-block" />Positive</span>
              <span className="flex items-center gap-1"><span className="w-2 h-2 bg-edge border border-edge-dark rounded-full inline-block" />Neutral</span>
              <span className="flex items-center gap-1"><span className="w-2 h-2 bg-danger/60 rounded-full inline-block" />Negative</span>
            </div>
          </div>

          {/* Common Topics */}
          <div className="bg-surface rounded-lg border border-edge p-5">
            <h3 className="font-display font-bold text-ink mb-3">Common Discussion Topics</h3>
            <div className="flex flex-wrap gap-2">
              {data.topics.map((topic, i) => {
                const sizes = ['text-lg', 'text-base', 'text-base', 'text-sm', 'text-sm', 'text-xs'];
                const opacities = ['opacity-100', 'opacity-90', 'opacity-80', 'opacity-70', 'opacity-60', 'opacity-50'];
                return (
                  <span key={topic} className={`${sizes[i]} ${opacities[i]} font-display font-bold text-primary px-3 py-1.5 bg-primary-light rounded-lg border border-primary/20`}>
                    {topic}
                  </span>
                );
              })}
            </div>
          </div>

          {/* Points */}
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div className="bg-surface rounded-lg border border-edge p-5">
              <h3 className="font-display font-bold text-ink mb-3 flex items-center gap-2">
                <span className="w-4 h-4 bg-success rounded-full flex items-center justify-center">
                  <svg className="w-2.5 h-2.5 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={3} d="M5 13l4 4L19 7" /></svg>
                </span>
                What Users Love
              </h3>
              <ul className="space-y-2">
                {data.positive_points.map(p => (
                  <li key={p} className="flex items-start gap-2 text-xs text-ink">
                    <span className="text-success mt-0.5">+</span>{p}
                  </li>
                ))}
              </ul>
            </div>
            <div className="bg-surface rounded-lg border border-edge p-5">
              <h3 className="font-display font-bold text-ink mb-3 flex items-center gap-2">
                <span className="w-4 h-4 bg-danger/60 rounded-full flex items-center justify-center">
                  <svg className="w-2.5 h-2.5 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={3} d="M20 12H4" /></svg>
                </span>
                Common Complaints
              </h3>
              <ul className="space-y-2">
                {data.negative_points.map(p => (
                  <li key={p} className="flex items-start gap-2 text-xs text-ink">
                    <span className="text-danger">−</span>{p}
                  </li>
                ))}
              </ul>
            </div>
          </div>

          {/* Overall opinion */}
          <div className="bg-surface rounded-lg border border-edge p-5">
            <h3 className="font-display font-bold text-ink mb-2">Overall Community Opinion</h3>
            <p className="text-sm text-muted leading-relaxed">{data.opinion}</p>
          </div>
        </div>
      )}
    </div>
  );
}
